# Generated by Django 4.2.5 on 2023-09-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_question_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(blank='true', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank='true', upload_to='images'),
        ),
    ]
